# ROCProfiler-Compute Jupyter Analysis Example

This notebook demonstrates how to use the Jupyter interface for rocprofiler-compute analysis.

## Prerequisites

1. You need to have profiling data collected using `rocprof-compute profile`
2. The data should be in a directory (e.g., `/path/to/workload_dir`)

## Basic Usage

In [18]:
# Import the Jupyter interface
import sys
from pathlib import Path

# Add the src directory to Python path
src_path = Path("../src").resolve()
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import rocprof_compute_jupyter as rc

## Load Performance Data

Use `rc.open()` to load your profiling data:

In [ ]:
# Replace with your actual data directory
perf_data_dir = "/home/feizheng/workspace/workloads/pc_test_stocha/MI325X/"

# Load the data
rc.open(perf_data_dir)

WARNING:root:roofline.csv not found.

## Display Analysis Results

Use `rc.analysis()` to display the analysis results:

In [20]:
# Display all basic metrics
rc.analysis()

'# ROCProfiler-Compute Analysis Results'

'**Data Directory:** /home/feizheng/workspace/workloads/pc_test_stocha/MI325X'

'**Architecture:** gfx942'

''

'## 0. Top Stats'

'### 0.1 Top Kernels'

,Kernel_Name,Count,Sum(ns),Mean(ns),Median(ns),Pct
0,"sgprbound(int, double*)",2,510261182.0,255130591.0,255130591.0,47.124958
1,"vgprbound(int, double*)",2,404419844.0,202209922.0,202209922.0,37.350025
2,"ldsbound(int, double*)",2,167087719.0,83543859.5,83543859.5,15.431316
3,"empty(int, double*)",2,1014576.0,507288.0,507288.0,0.093701

'### 0.2 Dispatch List'

   Dispatch_ID              Kernel_Name  GPU_ID
0            0  vgprbound(int, double*)       0
1            1  vgprbound(int, double*)       0
2            2   ldsbound(int, double*)       0
3            3   ldsbound(int, double*)       0
4            4  sgprbound(int, double*)       0
5            5  sgprbound(int, double*)       0
6            6      empty(int, double*)       0
7            7      empty(int, double*)       0

'## 1. System Info'

'### 1.1 System Info'

                                                                     Info
workload_name                                              pc_test_stocha
command                                                       ./occupancy
ip_blocks                            SQ|LDS|SQC|TA|TD|TCP|TCC|SPI|CPC|CPF
timestamp                                  Tue Oct 21 17:38:30 2025 (UTC)
version                                                                 3
hostname                                             banff-ccs-aus-g05-05
cpu_model                                 Intel(R) Xeon(R) Platinum 8480C
sbios                   American Megatrends International, LLC.C2789.5...
linux_distro                                           Ubuntu 24.04.3 LTS
linux_kernel_version                                   5.15.0-153-generic
amd_gpu_kernel_version                                                NaN
cpu_memory                                                     2113396976
gpu_memory                                                            NaN
rocm_version                                                        7.2.0
vbios                                                                 NaN
compute_partition                                                     SPX
memory_partition                                                     NPS1
gpu_series                                                          MI300
gpu_model                                                          MI325X
gpu_arch                                                           gfx942
gpu_chip_id                                                         29861
gpu_l1                                                                 32
gpu_l2                                                               4096
cu_per_gpu                                                            304
simd_per_cu                                                             4
se_per_gpu                                                             32
wave_size                                                              64
workgroup_max_size                                                   1024
max_waves_per_cu                                                       32
max_sclk                                                             2100
max_mclk                                                             1500
cur_sclk                                                             2100
cur_mclk                                                             1500
l2_banks                                                               16
total_l2_chan                                                         128
lds_banks_per_cu                                                       32
sqc_per_gpu                                                           160
pipes_per_gpu                                                           4
num_xcd                                                                 8
num_hbm_channels                                                      128

'## 2. System Speed-of-Light'

'### 2.1 System Speed-of-Light'

,Metric,Avg,Unit,Peak,Pct of Peak,Description
Metric_ID,,,,,,
2.1.0,VALU FLOPs,,Gflop/s,81715.2,,The total floating-point operations executed p...
2.1.1,VALU IOPs,,Giop/s,81715.2,,The total integer operations executed per seco...
2.1.2,MFMA FLOPs (F8),,Gflop/s,2614886.4,,The total number of 8-bit brain floating point...
2.1.3,MFMA FLOPs (BF16),,Gflop/s,1307443.2,,The total number of 16-bit brain floating poin...
2.1.4,MFMA FLOPs (F16),,Gflop/s,1307443.2,,The total number of 16-bit floating point MFMA...
2.1.5,MFMA FLOPs (F32),,Gflop/s,163430.4,,The total number of 32-bit floating point MFMA...
2.1.6,MFMA FLOPs (F64),,Gflop/s,163430.4,,The total number of 64-bit floating point MFMA...
2.1.7,MFMA IOPs (Int8),,Giop/s,2614886.4,,The total number of 8-bit integer MFMA operati...
2.1.8,Active CUs,,Cus,304,,Total number of active compute units (CUs) on ...
2.1.9,SALU Utilization,,Pct,100,,Indicates what percent of the kernel's duratio...
2.1.10,VALU Utilization,,Pct,100,,Indicates what percent of the kernel's duratio...
2.1.11,MFMA Utilization,,Pct,100,,Indicates what percent of the kernel's duratio...
2.1.12,VMEM Utilization,,Pct,100,,Indicates what percent of the kernel's duratio...
2.1.13,Branch Utilization,,Pct,100,,Indicates what percent of the kernel's duratio...
2.1.14,VALU Active Threads,,Threads,64,,Indicates the average level of divergence with...
2.1.15,IPC,,Instr/cycle,5,,The ratio of the total number of instructions ...
2.1.16,Wavefront Occupancy,,Wavefronts,9728,,The time-averaged number of wavefronts residen...
2.1.17,Theoretical LDS Bandwidth,,Gb/s,81715.2,,Indicates the maximum amount of bytes that cou...
2.1.18,LDS Bank Conflicts/Access,,Conflicts/access,32,,The ratio of the number of cycles spent in the...
2.1.19,vL1D Cache Hit Rate,,Pct,100,,The ratio of the number of vL1D cache line req...
2.1.20,vL1D Cache BW,,Gb/s,81715.2,,The number of bytes looked up in the vL1D cach...
2.1.21,L2 Cache Hit Rate,,Pct,100,,The ratio of the number of L2 cache line reque...
2.1.22,L2 Cache BW,,Gb/s,34406.4,,The number of bytes looked up in the L2 cache ...
2.1.23,L2-Fabric Read BW,,Gb/s,,,The number of bytes read by the L2 over the In...
2.1.24,L2-Fabric Write BW,,Gb/s,,,The number of bytes sent by the L2 over the In...
2.1.25,L2-Fabric Read Latency,,Cycles,,,The time-averaged number of cycles read reques...
2.1.26,L2-Fabric Write Latency,,Cycles,,,The time-averaged number of cycles write reque...
2.1.27,sL1D Cache Hit Rate,,Pct,100,,The percent of sL1D requests that hit on a pre...
2.1.28,sL1D Cache BW,,Gb/s,21504.0,,The number of bytes looked up in the sL1D cach...
2.1.29,L1I Hit Rate,,Pct,100,,The number of bytes looked up in the L1I cache...
2.1.30,L1I BW,,Gb/s,21504.0,,The percent of L1I requests that hit on a prev...
2.1.31,L1I Fetch Latency,,Cycles,,,The average number of cycles spent to fetch in...

'## 3. Memory Chart'

'### 3.1 Memory Chart'

,Metric,Value,Description
Metric_ID,,,
3.1.0,Wavefront Occupancy,,Wavefronts per active CU.
3.1.1,Wave Life,,Average number of cycles executing a wave.
3.1.2,SALU,,Total Number of SALU (Scalar ALU) instructions...
3.1.3,SMEM,,Total number of SMEM (Scalar Memory Read) inst...
3.1.4,VALU,,The number of VALU (Vector ALU) instructions i...
3.1.5,MFMA,,Total number of MFMA (Matrix-Fused-Multiply-Ad...
3.1.6,VMEM,,The number of VMEM (GPU Memory) read instructi...
3.1.7,LDS,,The total number of LDS instructions (includin...
3.1.8,GWS,,Total number of GDS (global data sync) instruc...
3.1.9,BR,,Total number of BRANCH instructions issued per...
3.1.10,Active CUs,,Total number of active compute units (CUs) on ...
3.1.11,Num CUs,304,Total number of compute units (CUs) on the acc...
3.1.12,VGPR,71.0,The number of architected vector general-purpo...
3.1.13,SGPR,72.0,The number of scalar general-purpose registers...
3.1.14,LDS Allocation,16384.0,"The number of bytes of LDS memory (or, shared ..."
3.1.15,Scratch Allocation,17.0,The number of bytes of scratch memory requeste...
3.1.16,Wavefronts,,"The total number of wavefronts, summed over al..."
3.1.17,Workgroups,,The total number of workgroups forming this ke...
3.1.18,LDS Req,,The total number of LDS instructions (includin...
3.1.19,LDS Util,,Indicates what percent of the kernel's duratio...
3.1.20,LDS Latency,,"The average number of round-trip cycles (i.e.,..."
3.1.21,VL1 Rd,,The total number of incoming read requests fro...
3.1.22,VL1 Wr,,The total number of incoming write requests fr...
3.1.23,VL1 Atomic,,The total number of incoming atomic requests f...
3.1.24,VL1 Hit,,The ratio of the number of vL1D cache line req...
3.1.25,VL1 Lat,,Calculated as the average number of cycles tha...
3.1.26,VL1 Coalesce,,Indicates how well memory instructions were co...
3.1.27,VL1 Stall,,The ratio of the number of cycles where the vL...
3.1.28,VL1_L2 Rd,,The number of read requests for a vL1D cache l...
3.1.29,VL1_L2 Wr,,The number of write requests to a vL1D cache l...
3.1.30,VL1_L2 Atomic,,The number of atomic requests that are sent th...
3.1.31,sL1D Rd,,"The total number of requests, of any size or t..."
3.1.32,sL1D Hit,,The total number of sL1D requests that hit on ...
3.1.33,sL1D Lat,,
3.1.34,sL1D_L2 Rd,,The total number of read requests from sL1D to...
3.1.35,sL1D_L2 Wr,,The total number of write requests from sL1D t...
3.1.36,sL1D_L2 Atomic,,The total number of atomic requests from sL1D ...
3.1.37,IL1 Fetch,,The total number of requests made to the L1I p...
3.1.38,IL1 Hit,,The percent of L1I requests that hit on a prev...
3.1.39,IL1 Lat,,The average number of cycles spent to fetch in...
3.1.40,IL1_L2 Rd,,The total number of requests across the L1I - ...
3.1.41,L2 Rd,,The total number of read requests to the L2 fr...
3.1.42,L2 Wr,,The total number of write requests to the L2 f...
3.1.43,L2 Atomic,,The total number of atomic requests (with and ...
3.1.44,L2 Hit,,The ratio of the number of L2 cache line reque...
3.1.45,Fabric_L2 Rd,,Number of L2 cache - Infinity Fabric read requ...
3.1.46,Fabric_L2 Wr,,Number of L2 cache - Infinity Fabric write req...
3.1.47,Fabric_L2 Atomic,,Number of L2 cache - Infinity Fabric write req...
3.1.48,Fabric Rd Lat,,The time-averaged number of cycles read reques...
3.1.49,Fabric Wr Lat,,The time-averaged number of cycles write reque...
3.1.50,Fabric Atomic Lat,,The time-averaged number of cycles atomic requ...
3.1.51,HBM Rd,,The total number of L2 requests to Infinity Fa...
3.1.52,HBM Wr,,The total number of L2 requests to Infinity Fa...

'## 4. Roofline'

'### 4.1 Roofline Performance Rates'

,Metric,Value,Unit,Peak (Empirical),Description
Metric_ID,,,,,
4.1.0,VALU FLOPs (F16),,Gflop/s,0,The total 16-bit floating-point operations exe...
4.1.1,VALU FLOPs (F32),,Gflop/s,0,The total 32-bit floating-point operations exe...
4.1.2,VALU FLOPs (F64),,Gflop/s,0,The total 64-bit floating-point operations exe...
4.1.3,MFMA FLOPs (F64),,Gflop/s,0,The total number of 64-bit floating point MFMA...
4.1.4,MFMA FLOPs (F32),,Gflop/s,0,The total number of 32-bit floating point MFMA...
4.1.5,MFMA FLOPs (F16),,Gflop/s,0,The total number of 16-bit floating point MFMA...
4.1.6,MFMA FLOPs (BF16),,Gflop/s,0,The total number of 16-bit brain floating poin...
4.1.7,MFMA FLOPs (F8),,Gflop/s,0,The total number of 8-bit brain floating point...
4.1.8,MFMA IOPs (Int8),,Giop/s,0,The total number of 8-bit integer MFMA operati...
4.1.9,HBM Bandwidth,,Gb/s,0,The total number of bytes read from and writte...
4.1.10,L2 Cache Bandwidth,,Gb/s,0,The number of bytes looked up in the L2 cache ...
4.1.11,L1 Cache Bandwidth,,Gb/s,0,The number of bytes looked up in the vL1D cach...
4.1.12,LDS Bandwidth,,Gb/s,0,Indicates the maximum amount of bytes that cou...

'### 4.2 Roofline Plot Points'

,Metric,Value,Unit,Description
Metric_ID,,,,
4.2.0,AI HBM,,Flops/byte,The Arithmetic Intensity (AI) relative to High...
4.2.1,AI L2,,Flops/byte,The Arithmetic Intensity (AI) relative to the ...
4.2.2,AI L1,,Flops/byte,The Arithmetic Intensity (AI) relative to the ...
4.2.3,Performance (GFLOPs),,Gflop/s,"The overall achieved performance, measured in ..."

''

'**Note:** To see detailed metrics, apply filters using filter_kernel, filter_gpu, or filter_dispatch parameters.'

## Advanced Usage

### Filter by Kernel

You can filter results to show specific kernels:

In [21]:
# Show analysis for specific kernel IDs
rc.analysis(filter_kernel=["0", "1"])

'# ROCProfiler-Compute Analysis Results'

'**Data Directory:** /home/feizheng/workspace/workloads/pc_test_stocha/MI325X'

'**Architecture:** gfx942'

''

'## 0. Top Stats'

'### 0.1 Top Kernels'

,Kernel_Name,Count,Sum(ns),Mean(ns),Median(ns),Pct
0,"sgprbound(int, double*)",2,510261182.0,255130591.0,255130591.0,47.124958
1,"vgprbound(int, double*)",2,404419844.0,202209922.0,202209922.0,37.350025
2,"ldsbound(int, double*)",2,167087719.0,83543859.5,83543859.5,15.431316
3,"empty(int, double*)",2,1014576.0,507288.0,507288.0,0.093701

'### 0.2 Dispatch List'

   Dispatch_ID              Kernel_Name  GPU_ID
0            0  vgprbound(int, double*)       0
1            1  vgprbound(int, double*)       0
2            2   ldsbound(int, double*)       0
3            3   ldsbound(int, double*)       0
4            4  sgprbound(int, double*)       0
5            5  sgprbound(int, double*)       0
6            6      empty(int, double*)       0
7            7      empty(int, double*)       0

'## 1. System Info'

'### 1.1 System Info'

                                                                     Info
workload_name                                              pc_test_stocha
command                                                       ./occupancy
ip_blocks                            SQ|LDS|SQC|TA|TD|TCP|TCC|SPI|CPC|CPF
timestamp                                  Tue Oct 21 17:38:30 2025 (UTC)
version                                                                 3
hostname                                             banff-ccs-aus-g05-05
cpu_model                                 Intel(R) Xeon(R) Platinum 8480C
sbios                   American Megatrends International, LLC.C2789.5...
linux_distro                                           Ubuntu 24.04.3 LTS
linux_kernel_version                                   5.15.0-153-generic
amd_gpu_kernel_version                                                NaN
cpu_memory                                                     2113396976
gpu_memory                                                            NaN
rocm_version                                                        7.2.0
vbios                                                                 NaN
compute_partition                                                     SPX
memory_partition                                                     NPS1
gpu_series                                                          MI300
gpu_model                                                          MI325X
gpu_arch                                                           gfx942
gpu_chip_id                                                         29861
gpu_l1                                                                 32
gpu_l2                                                               4096
cu_per_gpu                                                            304
simd_per_cu                                                             4
se_per_gpu                                                             32
wave_size                                                              64
workgroup_max_size                                                   1024
max_waves_per_cu                                                       32
max_sclk                                                             2100
max_mclk                                                             1500
cur_sclk                                                             2100
cur_mclk                                                             1500
l2_banks                                                               16
total_l2_chan                                                         128
lds_banks_per_cu                                                       32
sqc_per_gpu                                                           160
pipes_per_gpu                                                           4
num_xcd                                                                 8
num_hbm_channels                                                      128

'## 2. System Speed-of-Light'

'### 2.1 System Speed-of-Light'

,Metric,Avg,Unit,Peak,Pct of Peak,Description
Metric_ID,,,,,,
2.1.0,VALU FLOPs,,Gflop/s,,,The total floating-point operations executed p...
2.1.1,VALU IOPs,,Giop/s,,,The total integer operations executed per seco...
2.1.2,MFMA FLOPs (F8),,Gflop/s,,,The total number of 8-bit brain floating point...
2.1.3,MFMA FLOPs (BF16),,Gflop/s,,,The total number of 16-bit brain floating poin...
2.1.4,MFMA FLOPs (F16),,Gflop/s,,,The total number of 16-bit floating point MFMA...
2.1.5,MFMA FLOPs (F32),,Gflop/s,,,The total number of 32-bit floating point MFMA...
2.1.6,MFMA FLOPs (F64),,Gflop/s,,,The total number of 64-bit floating point MFMA...
2.1.7,MFMA IOPs (Int8),,Giop/s,,,The total number of 8-bit integer MFMA operati...
2.1.8,Active CUs,,Cus,,,Total number of active compute units (CUs) on ...
2.1.9,SALU Utilization,,Pct,,,Indicates what percent of the kernel's duratio...
2.1.10,VALU Utilization,,Pct,,,Indicates what percent of the kernel's duratio...
2.1.11,MFMA Utilization,,Pct,,,Indicates what percent of the kernel's duratio...
2.1.12,VMEM Utilization,,Pct,,,Indicates what percent of the kernel's duratio...
2.1.13,Branch Utilization,,Pct,,,Indicates what percent of the kernel's duratio...
2.1.14,VALU Active Threads,,Threads,,,Indicates the average level of divergence with...
2.1.15,IPC,,Instr/cycle,,,The ratio of the total number of instructions ...
2.1.16,Wavefront Occupancy,,Wavefronts,,,The time-averaged number of wavefronts residen...
2.1.17,Theoretical LDS Bandwidth,,Gb/s,,,Indicates the maximum amount of bytes that cou...
2.1.18,LDS Bank Conflicts/Access,,Conflicts/access,,,The ratio of the number of cycles spent in the...
2.1.19,vL1D Cache Hit Rate,,Pct,,,The ratio of the number of vL1D cache line req...
2.1.20,vL1D Cache BW,,Gb/s,,,The number of bytes looked up in the vL1D cach...
2.1.21,L2 Cache Hit Rate,,Pct,,,The ratio of the number of L2 cache line reque...
2.1.22,L2 Cache BW,,Gb/s,,,The number of bytes looked up in the L2 cache ...
2.1.23,L2-Fabric Read BW,,Gb/s,,,The number of bytes read by the L2 over the In...
2.1.24,L2-Fabric Write BW,,Gb/s,,,The number of bytes sent by the L2 over the In...
2.1.25,L2-Fabric Read Latency,,Cycles,,,The time-averaged number of cycles read reques...
2.1.26,L2-Fabric Write Latency,,Cycles,,,The time-averaged number of cycles write reque...
2.1.27,sL1D Cache Hit Rate,,Pct,,,The percent of sL1D requests that hit on a pre...
2.1.28,sL1D Cache BW,,Gb/s,,,The number of bytes looked up in the sL1D cach...
2.1.29,L1I Hit Rate,,Pct,,,The number of bytes looked up in the L1I cache...
2.1.30,L1I BW,,Gb/s,,,The percent of L1I requests that hit on a prev...
2.1.31,L1I Fetch Latency,,Cycles,,,The average number of cycles spent to fetch in...

'## 3. Memory Chart'

'### 3.1 Memory Chart'

,Metric,Value,Description
Metric_ID,,,
3.1.0,Wavefront Occupancy,,Wavefronts per active CU.
3.1.1,Wave Life,,Average number of cycles executing a wave.
3.1.2,SALU,,Total Number of SALU (Scalar ALU) instructions...
3.1.3,SMEM,,Total number of SMEM (Scalar Memory Read) inst...
3.1.4,VALU,,The number of VALU (Vector ALU) instructions i...
3.1.5,MFMA,,Total number of MFMA (Matrix-Fused-Multiply-Ad...
3.1.6,VMEM,,The number of VMEM (GPU Memory) read instructi...
3.1.7,LDS,,The total number of LDS instructions (includin...
3.1.8,GWS,,Total number of GDS (global data sync) instruc...
3.1.9,BR,,Total number of BRANCH instructions issued per...
3.1.10,Active CUs,,Total number of active compute units (CUs) on ...
3.1.11,Num CUs,,Total number of compute units (CUs) on the acc...
3.1.12,VGPR,,The number of architected vector general-purpo...
3.1.13,SGPR,,The number of scalar general-purpose registers...
3.1.14,LDS Allocation,,"The number of bytes of LDS memory (or, shared ..."
3.1.15,Scratch Allocation,,The number of bytes of scratch memory requeste...
3.1.16,Wavefronts,,"The total number of wavefronts, summed over al..."
3.1.17,Workgroups,,The total number of workgroups forming this ke...
3.1.18,LDS Req,,The total number of LDS instructions (includin...
3.1.19,LDS Util,,Indicates what percent of the kernel's duratio...
3.1.20,LDS Latency,,"The average number of round-trip cycles (i.e.,..."
3.1.21,VL1 Rd,,The total number of incoming read requests fro...
3.1.22,VL1 Wr,,The total number of incoming write requests fr...
3.1.23,VL1 Atomic,,The total number of incoming atomic requests f...
3.1.24,VL1 Hit,,The ratio of the number of vL1D cache line req...
3.1.25,VL1 Lat,,Calculated as the average number of cycles tha...
3.1.26,VL1 Coalesce,,Indicates how well memory instructions were co...
3.1.27,VL1 Stall,,The ratio of the number of cycles where the vL...
3.1.28,VL1_L2 Rd,,The number of read requests for a vL1D cache l...
3.1.29,VL1_L2 Wr,,The number of write requests to a vL1D cache l...
3.1.30,VL1_L2 Atomic,,The number of atomic requests that are sent th...
3.1.31,sL1D Rd,,"The total number of requests, of any size or t..."
3.1.32,sL1D Hit,,The total number of sL1D requests that hit on ...
3.1.33,sL1D Lat,,
3.1.34,sL1D_L2 Rd,,The total number of read requests from sL1D to...
3.1.35,sL1D_L2 Wr,,The total number of write requests from sL1D t...
3.1.36,sL1D_L2 Atomic,,The total number of atomic requests from sL1D ...
3.1.37,IL1 Fetch,,The total number of requests made to the L1I p...
3.1.38,IL1 Hit,,The percent of L1I requests that hit on a prev...
3.1.39,IL1 Lat,,The average number of cycles spent to fetch in...
3.1.40,IL1_L2 Rd,,The total number of requests across the L1I - ...
3.1.41,L2 Rd,,The total number of read requests to the L2 fr...
3.1.42,L2 Wr,,The total number of write requests to the L2 f...
3.1.43,L2 Atomic,,The total number of atomic requests (with and ...
3.1.44,L2 Hit,,The ratio of the number of L2 cache line reque...
3.1.45,Fabric_L2 Rd,,Number of L2 cache - Infinity Fabric read requ...
3.1.46,Fabric_L2 Wr,,Number of L2 cache - Infinity Fabric write req...
3.1.47,Fabric_L2 Atomic,,Number of L2 cache - Infinity Fabric write req...
3.1.48,Fabric Rd Lat,,The time-averaged number of cycles read reques...
3.1.49,Fabric Wr Lat,,The time-averaged number of cycles write reque...
3.1.50,Fabric Atomic Lat,,The time-averaged number of cycles atomic requ...
3.1.51,HBM Rd,,The total number of L2 requests to Infinity Fa...
3.1.52,HBM Wr,,The total number of L2 requests to Infinity Fa...

'## 4. Roofline'

'### 4.1 Roofline Performance Rates'

,Metric,Value,Unit,Peak (Empirical),Description
Metric_ID,,,,,
4.1.0,VALU FLOPs (F16),,Gflop/s,,The total 16-bit floating-point operations exe...
4.1.1,VALU FLOPs (F32),,Gflop/s,,The total 32-bit floating-point operations exe...
4.1.2,VALU FLOPs (F64),,Gflop/s,,The total 64-bit floating-point operations exe...
4.1.3,MFMA FLOPs (F64),,Gflop/s,,The total number of 64-bit floating point MFMA...
4.1.4,MFMA FLOPs (F32),,Gflop/s,,The total number of 32-bit floating point MFMA...
4.1.5,MFMA FLOPs (F16),,Gflop/s,,The total number of 16-bit floating point MFMA...
4.1.6,MFMA FLOPs (BF16),,Gflop/s,,The total number of 16-bit brain floating poin...
4.1.7,MFMA FLOPs (F8),,Gflop/s,,The total number of 8-bit brain floating point...
4.1.8,MFMA IOPs (Int8),,Giop/s,,The total number of 8-bit integer MFMA operati...
4.1.9,HBM Bandwidth,,Gb/s,,The total number of bytes read from and writte...
4.1.10,L2 Cache Bandwidth,,Gb/s,,The number of bytes looked up in the L2 cache ...
4.1.11,L1 Cache Bandwidth,,Gb/s,,The number of bytes looked up in the vL1D cach...
4.1.12,LDS Bandwidth,,Gb/s,,Indicates the maximum amount of bytes that cou...

'### 4.2 Roofline Plot Points'

,Metric,Value,Unit,Description
Metric_ID,,,,
4.2.0,AI HBM,,Flops/byte,The Arithmetic Intensity (AI) relative to High...
4.2.1,AI L2,,Flops/byte,The Arithmetic Intensity (AI) relative to the ...
4.2.2,AI L1,,Flops/byte,The Arithmetic Intensity (AI) relative to the ...
4.2.3,Performance (GFLOPs),,Gflop/s,"The overall achieved performance, measured in ..."

'## 5. Command Processor (CPC/CPF)'

'### 5.1 Command processor fetcher (CPF)'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
5.1.0,CPF Utilization,,,,Pct,Percent of total cycles where the CPF was busy...
5.1.1,CPF Stall,,,,Pct,Percent of CPF busy cycles where the CPF was s...
5.1.2,CPF-L2 Utilization,,,,Pct,Percent of total cycles counted by the CPF-L2 ...
5.1.3,CPF-L2 Stall,,,,Pct,Percent of CPF-L2 L2 busy cycles where the CPF...
5.1.4,CPF-UTCL1 Stall,,,,Pct,Percent of CPF busy cycles where the CPF was s...

'### 5.2 Command processor packet processor (CPC)'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
5.2.0,CPC Utilization,,,,Pct,Percent of total cycles where the CPC was busy...
5.2.1,CPC Stall Rate,,,,Pct,Percent of CPC busy cycles where the CPC was s...
5.2.2,CPC Packet Decoding Utilization,,,,Pct,Percent of CPC busy cycles spent decoding comm...
5.2.3,CPC-Workgroup Manager Utilization,,,,Pct,Percent of CPC busy cycles spent dispatching w...
5.2.4,CPC-L2 Utilization,,,,Pct,Percent of total cycles counted by the CPC-L2 ...
5.2.5,CPC-UTCL1 Stall,,,,Pct,Percent of CPC busy cycles where the CPC was s...
5.2.6,CPC-UTCL2 Utilization,,,,Pct,Percent of total cycles counted by the CPC's L...

'## 6. Workgroup Manager (SPI)'

'### 6.1 Workgroup manager utilizations'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
6.1.0,Accelerator Utilization,,,,Pct,The percent of cycles in the kernel where the ...
6.1.1,Scheduler-Pipe Utilization,,,,Pct,The percent of total scheduler-pipe cycles in ...
6.1.2,Workgroup Manager Utilization,,,,Pct,The percent of cycles in the kernel where the ...
6.1.3,Shader Engine Utilization,,,,Pct,The percent of total shader engine cycles in t...
6.1.4,SIMD Utilization,,,,Pct,The percent of total SIMD cycles in the kernel...
6.1.5,Dispatched Workgroups,,,,Workgroups,The total number of workgroups forming this ke...
6.1.6,Dispatched Wavefronts,,,,Wavefronts,"The total number of wavefronts, summed over al..."
6.1.7,VGPR Writes,,,,Cycles/wave,The average number of cycles spent initializin...
6.1.8,SGPR Writes,,,,Cycles/wave,The average number of cycles spent initializin...

'### 6.2 Workgroup Manager - Resource Allocation'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
6.2.0,Not-scheduled Rate (Workgroup Manager),,,,Pct,The percent of total scheduler-pipe cycles in ...
6.2.1,Not-scheduled Rate (Scheduler-Pipe),,,,Pct,The percent of total scheduler-pipe cycles in ...
6.2.2,Scheduler-Pipe Stall Rate,,,,Pct,The percent of total scheduler-pipe cycles in ...
6.2.3,Scratch Stall Rate,,,,Pct,The percent of total shader-engine cycles in t...
6.2.4,Insufficient SIMD Waveslots,,,,Pct,The percent of total SIMD cycles in the kernel...
6.2.5,Insufficient SIMD VGPRs,,,,Pct,The percent of total SIMD cycles in the kernel...
6.2.6,Insufficient SIMD SGPRs,,,,Pct,The percent of total SIMD cycles in the kernel...
6.2.7,Insufficient CU LDS,,,,Pct,The percent of total CU cycles in the kernel w...
6.2.8,Insufficient CU Barriers,,,,Pct,The percent of total CU cycles in the kernel w...
6.2.9,Reached CU Workgroup Limit,,,,Pct,The percent of total CU cycles in the kernel w...
6.2.10,Reached CU Wavefront Limit,,,,Pct,The percent of total CU cycles in the kernel w...

'## 7. Wavefront'

'### 7.1 Wavefront Launch Stats'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
7.1.0,Grid Size,,,,Work items,"The total number of work-items (or, threads) l..."
7.1.1,Workgroup Size,,,,Work items,"The total number of work-items (or, threads) i..."
7.1.2,Total Wavefronts,,,,Wavefronts,The total number of wavefronts launched as par...
7.1.3,Saved Wavefronts,,,,Wavefronts,The total number of wavefronts saved at a cont...
7.1.4,Restored Wavefronts,,,,Wavefronts,The total number of wavefronts restored from a...
7.1.5,VGPRs,,,,Registers,The number of architected vector general-purpo...
7.1.6,AGPRs,,,,Registers,The number of accumulation vector general-purp...
7.1.7,SGPRs,,,,Registers,The number of scalar general-purpose registers...
7.1.8,LDS Allocation,,,,Bytes,"The number of bytes of LDS memory (or, shared ..."
7.1.9,Scratch Allocation,,,,Bytes/workitem,The number of bytes of scratch memory requeste...

'### 7.2 Wavefront Runtime Stats'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
7.2.0,Kernel Time,,,,Ns,The total duration of the executed kernel.
7.2.1,Kernel Time (Cycles),,,,Cycle,The total duration of the executed kernel in c...
7.2.2,Instructions per wavefront,,,,Instr/wavefront,The average number of instructions (of all typ...
7.2.3,Wave Cycles,,,,Cycles per wave,The number of cycles a wavefront in the kernel...
7.2.4,Dependency Wait Cycles,,,,Cycles per wave,The number of cycles a wavefront in the kernel...
7.2.5,Issue Wait Cycles,,,,Cycles per wave,The number of cycles a wavefront in the kernel...
7.2.6,Active Cycles,,,,Cycles per wave,The average number of cycles a wavefront in th...
7.2.7,Wavefront Occupancy,,,,Wavefronts,The time-averaged number of wavefronts residen...

'## 10. Compute Units - Instruction Mix'

'### 10.1 Overall Instruction Mix'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '# of instr per wave=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAA==', 'dtype': 'i1'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAA==', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['VALU', 'VMEM', 'LDS', 'MFMA', 'SALU', 'SMEM', 'Branch'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'colorbar': {'title': {'text': '# of instr per wave'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '# of instr per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 10.2 VALU Arithmetic Instruction Mix'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '# of instr per wave=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAA', 'dtype': 'i1'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAA', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['INT32', 'INT64', 'F16-ADD', 'F16-MUL', 'F16-FMA', 'F16-Trans',
                          'F32-ADD', 'F32-MUL', 'F32-FMA', 'F32-Trans', 'F64-ADD', 'F64-MUL',
                          'F64-FMA', 'F64-Trans', 'Conversion'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'colorbar': {'title': {'text': '# of instr per wave'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '# of instr per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 10.3 VMEM Instruction Mix'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
10.3.0,Global/Generic Instr,,,,Instr per wave,The total number of global & generic memory in...
10.3.1,Global/Generic Read,,,,Instr per wave,The total number of global & generic memory re...
10.3.2,Global/Generic Write,,,,Instr per wave,The total number of global & generic memory wr...
10.3.3,Global/Generic Atomic,,,,Instr per wave,The total number of global & generic memory at...
10.3.4,Spill/Stack Instr,,,,Instr per wave,The total number of spill/stack memory instruc...
10.3.5,Spill/Stack Read,,,,Instr per wave,The total number of spill/stack memory read in...
10.3.6,Spill/Stack Write,,,,Instr per wave,The total number of spill/stack memory write i...
10.3.7,Spill/Stack Atomic,,,,Instr per wave,The total number of spill/stack memory atomic ...

'### 10.4 MFMA Arithmetic Instruction Mix'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
10.4.0,MFMA-I8,,,,Instr per wave,The total number of 8-bit integer MFMA instruc...
10.4.1,MFMA-F8,,,,Instr per wave,The total number of 8-bit floating point MFMA ...
10.4.2,MFMA-F16,,,,Instr per wave,The total number of 16-bit floating point MFMA...
10.4.3,MFMA-BF16,,,,Instr per wave,The total number of 16-bit brain floating poin...
10.4.4,MFMA-F32,,,,Instr per wave,The total number of 32-bit floating-point MFMA...
10.4.5,MFMA-F64,,,,Instr per wave,The total number of 64-bit floating-point MFMA...

'## 11. Compute Units - Compute Pipeline'

'### 11.1 Compute Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Pct of Peak=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAA=='),
                                   'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['VALU FLOPs', 'VALU IOPs', 'MFMA FLOPs (F8)', 'MFMA FLOPs (BF16)',
                          'MFMA FLOPs (F16)', 'MFMA FLOPs (F32)', 'MFMA FLOPs (F64)',
                          'MFMA IOPs (INT8)'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': 'Pct of Peak'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 110], 'title': {'text': 'Pct of Peak'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 11.2 Pipeline Statistics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
11.2.0,IPC,,,,Instr/cycle,The ratio of the total number of instructions ...
11.2.1,IPC (Issued),,,,Instr/cycle,The ratio of the total number of (non-internal...
11.2.2,SALU Utilization,,,,Pct,Indicates what percent of the kernel's duratio...
11.2.3,VALU Utilization,,,,Pct,Indicates what percent of the kernel's duratio...
11.2.4,VMEM Utilization,,,,Pct,Indicates what percent of the kernel's duratio...
11.2.5,Branch Utilization,,,,Pct,Indicates what percent of the kernel's duratio...
11.2.6,VALU Active Threads,,,,Threads,Indicates the average level of divergence with...
11.2.7,MFMA Utilization,,,,Pct,Indicates what percent of the kernel's duratio...
11.2.8,MFMA Instruction Cycles,,,,Cycles/instr,The average duration of MFMA instructions in t...
11.2.9,VMEM Latency,,,,Cycles,The average number of round-trip cycles (that ...
11.2.10,SMEM Latency,,,,Cycles,The average number of round-trip cycles (that ...

'### 11.3 Arithmetic Operations'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
11.3.0,FLOPs (Total),,,,Ops per wave,The total number of floating-point operations ...
11.3.1,IOPs (Total),,,,Ops per wave,The total number of integer operations execute...
11.3.2,F8 OPs,,,,Ops per wave,
11.3.3,F16 OPs,,,,Ops per wave,The total number of 16-bit floating-point oper...
11.3.4,BF16 OPs,,,,Ops per wave,The total number of 16-bit brain floating-poin...
11.3.5,F32 OPs,,,,Ops per wave,The total number of 32-bit floating-point oper...
11.3.6,F64 OPs,,,,Ops per wave,The total number of 64-bit floating-point oper...
11.3.7,INT8 OPs,,,,Ops per wave,The total number of 8-bit integer operations e...

'## 12. Local Data Share (LDS)'

'### 12.1 LDS Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '%=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Utilization', 'Access Rate', 'Theoretical Bandwidth Utilization',
                          'Bank Conflict Rate'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': '%'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 110], 'title': {'text': '%'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 12.2 LDS Statistics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
12.2.0,LDS Instructions,,,,Instr per wave,The total number of LDS instructions (includin...
12.2.1,Theoretical Bandwidth,,,,Gbps,Indicates the maximum amount of bytes that cou...
12.2.2,LDS Latency,,,,Cycles,"The average number of round-trip cycles (i.e.,..."
12.2.3,Bank Conflicts/Access,,,,Conflicts/access,The ratio of the number of cycles spent in the...
12.2.4,Index Accesses,,,,Cycles per wave,The total number of cycles spent in the LDS sc...
12.2.5,Atomic Return Cycles,,,,Cycles per wave,The total number of cycles spent on LDS atomic...
12.2.6,Bank Conflict,,,,Cycles per wave,The total number of cycles spent in the LDS sc...
12.2.7,Addr Conflict,,,,Cycles per wave,The total number of cycles spent in the LDS sc...
12.2.8,Unaligned Stall,,,,Cycles per wave,The total number of cycles spent in the LDS sc...
12.2.9,Mem Violations,,,,Accesses per wave,The total number of out-of-bounds accesses mad...

'## 13. Instruction Cache'

'### 13.1 L1I Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '%=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Bandwidth Utilization', 'Cache Hit Rate',
                          'L1I-L2 Bandwidth Utilization'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': '%'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 110], 'title': {'text': '%'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 13.2 L1I cache accesses'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
13.2.0,Req,,,,Req per wave,The total number of requests made to the L1I p...
13.2.1,Hits,,,,Hits per wave,The total number of L1I requests that hit on a...
13.2.2,Misses - Non Duplicated,,,,Misses per wave,The total number of L1I requests that missed o...
13.2.3,Misses - Duplicated,,,,Misses per wave,The total number of L1I requests that missed o...
13.2.4,Cache Hit Rate,,,,Pct,The percent of L1I requests that hit [#l1i-cac...
13.2.5,Instruction Fetch Latency,,,,Cycles,The average number of cycles spent to fetch in...

'### 13.3 L1I <-> L2 interface'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
13.3.0,L1I-L2 Bandwidth,,,,Gbps,Total number of bytes transferred across L1I -...

'## 14. Scalar L1 Data Cache'

'### 14.1 Scalar L1D Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '%=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Bandwidth Utilization', 'Cache Hit Rate', 'sL1D-L2 BW Utilization'],
                         dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': '%'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 110], 'title': {'text': '%'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 14.2 Scalar L1D cache accesses'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
14.2.0,Req,,,,Req per wave,"The total number of requests, of any size or t..."
14.2.1,Hits,,,,Req per wave,The total number of sL1D requests that hit on ...
14.2.2,Misses - Non Duplicated,,,,Req per wave,The total number of sL1D requests that missed ...
14.2.3,Misses- Duplicated,,,,Req per wave,The total number of sL1D requests that missed ...
14.2.4,Cache Hit Rate,,,,Pct,Indicates the percent of sL1D requests that hi...
14.2.5,Read Req (Total),,,,Req per wave,The total number of sL1D read requests of any ...
14.2.6,Atomic Req,,,,Req per wave,The total number of atomic requests from sL1D ...
14.2.7,Read Req (1 DWord),,,,Req per wave,The total number of sL1D read requests made fo...
14.2.8,Read Req (2 DWord),,,,Req per wave,The total number of sL1D read requests made fo...
14.2.9,Read Req (4 DWord),,,,Req per wave,The total number of sL1D read requests made fo...
14.2.10,Read Req (8 DWord),,,,Req per wave,The total number of sL1D read requests made fo...
14.2.11,Read Req (16 DWord),,,,Req per wave,The total number of sL1D read requests made fo...

'### 14.3 Scalar L1D Cache - L2 Interface'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
14.3.0,sL1D-L2 BW,,,,Gbps,"The total number of bytes read from, written t..."
14.3.1,Read Req,,,,Req per wave,The total number of read requests from sL1D to...
14.3.2,Write Req,,,,Req per wave,The total number of write requests from sL1D t...
14.3.3,Atomic Req,,,,Req per wave,The total number of atomic requests from sL1D ...
14.3.4,Stall Cycles,,,,Cycles per wave,The total number of cycles the sL1D\u2194L2 in...

'## 15. Address Processing Unit and Data Return Path (TA/TD)'

'### 15.1 Busy and stall metrics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
15.1.0,Address Processing Unit Busy,,,,Pct,Percent of the total CU cycles the address pro...
15.1.1,Address Stall,,,,Pct,Percent of the total CU cycles the address pro...
15.1.2,Data Stall,,,,Pct,Percent of the total CU cycles the address pro...
15.1.3,Data-Processor → Address Stall,,,,Pct,Percent of total CU cycles the address process...
15.1.4,Sequencer → TA Address Stall,,,,Cycles per wave,
15.1.5,Sequencer → TA Command Stall,,,,Cycles per wave,
15.1.6,Sequencer → TA Data Stall,,,,Cycles per wave,

'### 15.2 Instruction counts'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
15.2.0,Total Instructions,,,,Instructions per wave,The total number of memory instructions execut...
15.2.1,Global/Generic Instructions,,,,Instructions per wave,The total number of global & generic memory in...
15.2.2,Global/Generic Read Instructions,,,,Instructions per wave,The total number of global & generic memory re...
15.2.3,Global/Generic Write Instructions,,,,Instructions per wave,The total number of global & generic memory wr...
15.2.4,Global/Generic Atomic Instructions,,,,Instructions per wave,The total number of global & generic memory at...
15.2.5,Spill/Stack Instructions,,,,Instructions per wave,The total number of spill/stack memory instruc...
15.2.6,Spill/Stack Read Instructions,,,,Instructions per wave,The total number of spill/stack memory read in...
15.2.7,Spill/Stack Write Instructions,,,,Instructions per wave,The total number of spill/stack memory write i...
15.2.8,Spill/Stack Atomic Instructions,,,,Instructions per wave,The total number of spill/stack memory atomic ...

'### 15.3 Spill and stack metrics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
15.3.0,Spill/Stack Total Cycles,,,,Cycles per wave,The number of cycles the address processing un...
15.3.1,Spill/Stack Coalesced Read,,,,Cycles per wave,The number of cycles the address processing un...
15.3.2,Spill/Stack Coalesced Write,,,,Cycles per wave,The number of cycles the address processing un...

'### 15.4 Vector L1 data-return path or Texture Data (TD)'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
15.4.0,Data-Return Busy,,,,Pct,Percent of the total CU cycles the data-return...
15.4.1,Cache RAM → Data-Return Stall,,,,Pct,Percent of the total CU cycles the data-return...
15.4.2,Workgroup manager → Data-Return Stall,,,,Pct,Percent of the total CU cycles the data-return...
15.4.3,Coalescable Instructions,,,,Instructions per wave,The number of instructions submitted to the da...
15.4.4,Read Instructions,,,,Instructions per wave,The number of read instructions submitted to t...
15.4.5,Write Instructions,,,,Instructions per wave,The number of store instructions submitted to ...
15.4.6,Atomic Instructions,,,,Instructions per wave,The number of atomic instructions submitted to...

'## 16. Vector L1 Data Cache'

'### 16.1 vL1D Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '%=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Hit rate', 'Bandwidth Utilization', 'Utilization', 'Coalescing'],
                         dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': '%'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 400,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 110], 'title': {'text': '%'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 16.2 vL1D cache stall metrics'

,Metric,Min,Q1,Median,Q3,Max,Description
Metric_ID,,,,,,,
16.2.0,Stalled on L2 Data,,,,,,The ratio of the number of cycles where the vL...
16.2.1,Stalled on L2 Req,,,,,,The ratio of the number of cycles where the vL...
16.2.2,Tag RAM Stall (Read),,,,,,The ratio of the number of cycles where the vL...
16.2.3,Tag RAM Stall (Write),,,,,,The ratio of the number of cycles where the vL...
16.2.4,Tag RAM Stall (Atomic),,,,,,The ratio of the number of cycles where the vL...

'### 16.3 vL1D cache access metrics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
16.3.0,Total Req,,,,Req per wave,The total number of incoming requests from the...
16.3.1,Read Req,,,,Req per wave,The total number of incoming read requests fro...
16.3.2,Write Req,,,,Req per wave,The total number of incoming write requests fr...
16.3.3,Atomic Req,,,,Req per wave,The total number of incoming atomic requests f...
16.3.4,Cache BW,,,,Gbps,The number of bytes looked up in the vL1D cach...
16.3.5,Cache Hit Rate,,,,Pct,The ratio of the number of vL1D cache line req...
16.3.6,Cache Accesses,,,,Req per wave,The total number of cache line lookups in the ...
16.3.7,Cache Hits,,,,Req per wave,The number of cache accesses minus the number ...
16.3.8,Invalidations,,,,Req per wave,The number of times the vL1D was issued a writ...
16.3.9,L1-L2 BW,,,,Gbps,The number of bytes transferred across the vL1...
16.3.10,L1-L2 Read,,,,Req per wave,The number of read requests for a vL1D cache l...
16.3.11,L1-L2 Write,,,,Req per wave,The number of write requests to a vL1D cache l...
16.3.12,L1-L2 Atomic,,,,Req per wave,The number of atomic requests that are sent th...

'### 16.4 L1D - L2 Transactions'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Req per wave=%{x}<br>=%{y}<br>text=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAA', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Read', 'Write', 'Atomic'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'font': {'color': '#ffffff'},
               'height': 200,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'title': {'text': 'NC', 'x': 0.5},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'rangemode': 'nonnegative',
                         'showgrid': False,
                         'title': {'text': 'Req per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'showgrid': False, 'title': {'text': ''}}}
})

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Req per wave=%{x}<br>=%{y}<br>text=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAA', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Read', 'Write', 'Atomic'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'font': {'color': '#ffffff'},
               'height': 200,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'title': {'text': 'UC', 'x': 0.5},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'rangemode': 'nonnegative',
                         'showgrid': False,
                         'title': {'text': 'Req per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'showgrid': False, 'title': {'text': ''}}}
})

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Req per wave=%{x}<br>=%{y}<br>text=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAA', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Read', 'Write', 'Atomic'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'font': {'color': '#ffffff'},
               'height': 200,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'title': {'text': 'CC', 'x': 0.5},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'rangemode': 'nonnegative',
                         'showgrid': False,
                         'title': {'text': 'Req per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'showgrid': False, 'title': {'text': ''}}}
})

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Req per wave=%{x}<br>=%{y}<br>text=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAA', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Read', 'Write', 'Atomic'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'font': {'color': '#ffffff'},
               'height': 200,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'title': {'text': 'RW', 'x': 0.5},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'rangemode': 'nonnegative',
                         'showgrid': False,
                         'title': {'text': 'Req per wave'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'showgrid': False, 'title': {'text': ''}}}
})

'### 16.5 L1 Unified Translation Cache (UTCL1)'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
16.5.0,Req,,,,Req per wave,The number of translation requests made to the...
16.5.1,Hit Ratio,,,,Pct,The ratio of the number of translation request...
16.5.2,Hits,,,,Req per wave,The number of translation requests that hit in...
16.5.3,Translation Misses,,,,Req per wave,The total number of translation requests that ...
16.5.4,Permission Misses,,,,Req per wave,The total number of translation requests that ...

'### 16.6 L1D Addr Translation Stalls'

WARNING:root:[analysis] Table 1606 is empty

'## 17. L2 Cache'

'### 17.1 L2 Speed-of-Light'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '%=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Utilization', 'Peak Bandwidth', 'Hit Rate'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 100,
                             'cmin': 0,
                             'colorbar': {'title': {'text': '%'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 220,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'range': [0, 110],
                         'ticks': 'inside',
                         'title': {'text': '%'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'GB/s=%{marker.color}<br>Metric=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['L2-Fabric Read BW', 'L2-Fabric Write and Atomic BW', 'HBM Bandwidth'],
                         dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'cmax': 0.0,
                             'cmin': 0,
                             'colorbar': {'title': {'text': 'GB/s'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'font': {'color': '#ffffff'},
               'height': 220,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'range': [0, 0.0], 'title': {'text': 'GB/s'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Metric'}}}
})

'### 17.2 L2-Fabric interface metrics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
17.2.0,Read BW,,,,Gbps,The total number of bytes read by the L2 cache...
17.2.1,HBM Read Traffic,,,,Pct,The percent of read requests generated by the ...
17.2.2,Remote Read Traffic,,,,Pct,The percent of read requests generated by the ...
17.2.3,Uncached Read Traffic,,,,Pct,The percent of read requests generated by the ...
17.2.4,Write and Atomic BW,,,,Gbps,The total number of bytes written by the L2 ov...
17.2.5,HBM Write and Atomic Traffic,,,,Pct,The percent of write and atomic requests gener...
17.2.6,Remote Write and Atomic Traffic,,,,Pct,The percent of read requests generated by the ...
17.2.7,Atomic Traffic,,,,Pct,The percent of write requests generated by the...
17.2.8,Uncached Write and Atomic Traffic,,,,Pct,The percent of write and atomic requests gener...
17.2.9,Read Latency,,,,Cycles,The time-averaged number of cycles read reques...
17.2.10,Write and Atomic Latency,,,,Cycles,The time-averaged number of cycles write reque...
17.2.11,Atomic Latency,,,,Cycles,The time-averaged number of cycles atomic requ...

'### 17.3 L2 Cache Accesses'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
17.3.0,Bandwidth,,,,Gbps,"The number of bytes looked up in the L2 cache,..."
17.3.1,Req,,,,Req per wave,The total number of incoming requests to the L...
17.3.2,Read Req,,,,Req per wave,The total number of read requests to the L2 fr...
17.3.3,Write Req,,,,Req per wave,The total number of write requests to the L2 f...
17.3.4,Atomic Req,,,,Req per wave,The total number of atomic requests (with and ...
17.3.5,Streaming Req,,,,Req per wave,The total number of incoming requests to the L...
17.3.6,Probe Req,,,,Req per wave,The number of coherence probe requests made to...
17.3.7,Cache Hit,,,,Pct,The ratio of the number of L2 cache line reque...
17.3.8,Hits,,,,Hits per wave,The total number of requests to the L2 from al...
17.3.9,Misses,,,,Misses per wave,The total number of requests to the L2 from al...
17.3.10,Writeback,,,,Cachelines per wave,The total number of L2 cache lines written bac...
17.3.11,Writeback (Internal),,,,Cachelines per wave,The total number of L2 cache lines written bac...
17.3.12,Writeback (vL1D Req),,,,Cachelines per wave,The total number of L2 cache lines written bac...
17.3.13,Evict (Internal),,,,Cachelines per wave,The total number of L2 cache lines evicted fro...
17.3.14,Evict (vL1D Req),,,,Cachelines per wave,The total number of L2 cache lines evicted fro...
17.3.15,NC Req,,,,Req per wave,The total number of requests to the L2 to Not-...
17.3.16,UC Req,,,,Req per wave,The total number of requests to the L2 that go...
17.3.17,CC Req,,,,Req per wave,The total number of requests to the L2 that go...
17.3.18,RW Req,,,,Req per wave,The total number of requests to the L2 that go...

'### 17.4 L2 Cache Stalls'

WARNING:root:[analysis] Table 1704 is empty

'### 17.5 L2 - Fabric Interface stalls'

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Pct=%{x}<br>=%{y}<br>text=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'text': {'bdata': 'AAAAAAAAAAA=', 'dtype': 'f8'},
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'AA==', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['Credit Starvation'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'font': {'color': '#ffffff'},
               'height': 200,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 50, 'l': 50, 'pad': 4, 'r': 50, 't': 50},
               'paper_bgcolor': 'rgba(0,0,0,0)',
               'plot_bgcolor': 'rgba(0,0,0,0)',
               'template': '...',
               'title': {'text': 'Write', 'x': 0.5},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'rangemode': 'nonnegative',
                         'showgrid': False,
                         'title': {'text': 'Pct'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'showgrid': False, 'title': {'text': ''}}}
})

'### 17.6 L2 - Fabric interface detailed metrics'

,Metric,Avg,Min,Max,Unit,Description
Metric_ID,,,,,,
17.6.0,Read (32B),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.1,Read (64B),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.2,Read (128B),,,,Req per wave,
17.6.3,Read (Uncached),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.4,HBM Read,,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.5,Remote Read,,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.6,Write and Atomic (32B),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.7,Write and Atomic (Uncached),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.8,Write and Atomic (64B),,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.9,HBM Write and Atomic,,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.10,Remote Write and Atomic,,,,Req per wave,The total number of L2 requests to Infinity Fa...
17.6.11,Atomic,,,,Req per wave,The total number of L2 requests to Infinity Fa...

'## 18. L2 Cache (per Channel)'

'### 18.1 Aggregate Stats (All channels)'

,Metric,Avg,Std Dev,Min,Max,Unit,Description
Metric_ID,,,,,,,
18.1.0,L2 Cache Hit Rate,,,,,Pct,The percent of total number of requests to the...

'### 18.2 L2 Cache Hit Rate (pct)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.2.0
18.2.1
18.2.2
18.2.3
18.2.4
...           ...  .. ..    ... ..  ..         ...
18.2.123
18.2.124
18.2.125
18.2.126
18.2.127

[128 rows x 7 columns]

'### 18.3 L2 Requests (per normUnit)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.3.0
18.3.1
18.3.2
18.3.3
18.3.4
...           ...  .. ..    ... ..  ..         ...
18.3.123
18.3.124
18.3.125
18.3.126
18.3.127

[128 rows x 7 columns]

'### 18.4 L2 Requests (per normUnit)'

          Channel L2 Read L2 Write L2 Atomic Description
Metric_ID
18.4.0
18.4.1
18.4.2
18.4.3
18.4.4
...           ...     ...      ...       ...         ...
18.4.123
18.4.124
18.4.125
18.4.126
18.4.127

[128 rows x 5 columns]

'### 18.5 L2-Fabric Requests (per normUnit)'

,Channel,L2-Fabric Read,L2-Fabric Write and Atomic,L2-Fabric Atomic,Description
Metric_ID,,,,,
18.5.0,,,,,
18.5.1,,,,,
18.5.2,,,,,
18.5.3,,,,,
18.5.4,,,,,
...,...,...,...,...,...
18.5.123,,,,,
18.5.124,,,,,
18.5.125,,,,,
18.5.126,,,,,
18.5.127,,,,,

'### 18.6 L2-Fabric Read Latency (Cycles)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.6.0
18.6.1
18.6.2
18.6.3
18.6.4
...           ...  .. ..    ... ..  ..         ...
18.6.123
18.6.124
18.6.125
18.6.126
18.6.127

[128 rows x 7 columns]

'### 18.7 L2-Fabric Write and Atomic Latency (Cycles)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.7.0
18.7.1
18.7.2
18.7.3
18.7.4
...           ...  .. ..    ... ..  ..         ...
18.7.123
18.7.124
18.7.125
18.7.126
18.7.127

[128 rows x 7 columns]

'### 18.8 L2-Fabric Atomic Latency (Cycles)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.8.0
18.8.1
18.8.2
18.8.3
18.8.4
...           ...  .. ..    ... ..  ..         ...
18.8.123
18.8.124
18.8.125
18.8.126
18.8.127

[128 rows x 7 columns]

'### 18.9 L2-Fabric Read Stall (Cycles per normUnit)'

,Channel,L2-Fabric Read Stall (PCIe),L2-Fabric Read Stall (Infinity Fabric™),L2-Fabric Read Stall (HBM),Description
Metric_ID,,,,,
18.9.0,,,,,
18.9.1,,,,,
18.9.2,,,,,
18.9.3,,,,,
18.9.4,,,,,
...,...,...,...,...,...
18.9.123,,,,,
18.9.124,,,,,
18.9.125,,,,,
18.9.126,,,,,
18.9.127,,,,,

'### 18.10 L2-Fabric Write and Atomic Stall (Cycles per normUnit)'

,Channel,L2-Fabric Write Stall (PCIe),L2-Fabric Write Stall (Infinity Fabric™),L2-Fabric Write Stall (HBM),L2-Fabric Write Starve,Description
Metric_ID,,,,,,
18.10.0,,,,,,
18.10.1,,,,,,
18.10.2,,,,,,
18.10.3,,,,,,
18.10.4,,,,,,
...,...,...,...,...,...,...
18.10.123,,,,,,
18.10.124,,,,,,
18.10.125,,,,,,
18.10.126,,,,,,
18.10.127,,,,,,

'### 18.12 L2-Fabric (128B read requests per normUnit)'

          Channel Min Q1 Median Q3 Max Description
Metric_ID
18.12.0
18.12.1
18.12.2
18.12.3
18.12.4
...           ...  .. ..    ... ..  ..         ...
18.12.123
18.12.124
18.12.125
18.12.126
18.12.127

[128 rows x 7 columns]

'## 21. PC Sampling'

'### 21.1 PC Sampling'

,source_line,Kernel_Name,instruction,count
6,.../__clang_hip_math.h:1099,"vgprbound(int, double*)","v_lshlrev_b32_e32 v93, 30, v101",219726
5,.../__clang_hip_math.h:1025,"vgprbound(int, double*)","v_mov_b64_e32 v[110:111], v[74:75]",219517
15,.../occupancy.hip:56,"ldsbound(int, double*)","ds_write_b64 v4, v[2:3]",12390
11,.../occupancy.hip:46,"vgprbound(int, double*)","v_mov_b32_e32 v92, v0",12182
18,.../occupancy.hip:60,"ldsbound(int, double*)","ds_read_b64 v[62:63], v7",9223
4,.../amd_warp_functions.h:145,"vgprbound(int, double*)","v_lshlrev_b32_e32 v37, 2, v37",5222
1,.../amd_device_functions.h:692,"ldsbound(int, double*)",s_barrier,4855
9,.../occupancy.hip:44,"vgprbound(int, double*)","s_or_b64 exec, exec, s[0:1]",4660
12,.../occupancy.hip:47,"vgprbound(int, double*)","v_mov_b32_e32 v1, v35",3925
16,.../occupancy.hip:58,"ldsbound(int, double*)","s_mov_b32 s59, 0xbfc55555",3414
17,.../occupancy.hip:59,"ldsbound(int, double*)",s_cbranch_execz 529,2577
19,.../occupancy.hip:62,"ldsbound(int, double*)","ds_write_b64 v1, v[4:5]",2411
3,.../amd_warp_functions.h:144,"vgprbound(int, double*)","v_and_or_b32 v37, s58, 63, v96",2403
22,.../occupancy.hip:72,"sgprbound(int, double*)","scratch_store_dwordx2 off, v[2:3], off offset:40",1457
10,.../occupancy.hip:45,"vgprbound(int, double*)","s_add_i32 s58, s58, 1",1385
23,.../occupancy.hip:74,"sgprbound(int, double*)","v_mov_b64_e32 v[54:55], v[0:1]",1211
20,.../occupancy.hip:64,"ldsbound(int, double*)","v_cmp_eq_f64_e32 vcc, v[4:5], v[0:1]",106
24,.../occupancy.hip:75,"sgprbound(int, double*)","v_add_f64 v[0:1], v[0:1], v[2:3]",101
0,.../amd_device_functions.h:691,"ldsbound(int, double*)",s_waitcnt lgkmcnt(0),89
2,.../amd_hip_runtime.h:254,"ldsbound(int, double*)","s_load_dword s33, s[0:1], 0x0",65
21,.../occupancy.hip:65,"ldsbound(int, double*)",s_endpgm,54
7,.../occupancy.hip:37,"empty(int, double*)",s_endpgm,40
13,.../occupancy.hip:49,"vgprbound(int, double*)","v_cvt_f64_i32_e32 v[0:1], s33",38
25,.../occupancy.hip:78,"sgprbound(int, double*)",s_waitcnt lgkmcnt(0),27
8,.../occupancy.hip:41,"vgprbound(int, double*)","s_load_dword s33, s[0:1], 0x0",7
26,.../occupancy.hip:79,"sgprbound(int, double*)",s_endpgm,7
14,.../occupancy.hip:50,"vgprbound(int, double*)",s_endpgm,5
27,".../Unrecognized code object id, physical virt...","vgprbound(int, double*)",None,1

### Filter by GPU

Filter results by GPU ID:

In [22]:
# Show analysis for specific GPU
rc.analysis(filter_gpu=[0])

ERROR:root:[analysis] [0] is an invalid gpu-id

SystemExit: 1

/home/feizheng/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3557: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.

### Filter by Dispatch

Filter results by dispatch ID:

In [ ]:
# Show analysis for specific dispatches
rc.analysis(filter_dispatch=[0, 1, 2])

## Working with DataFrames

### List Available Tables

See what tables are available:

In [ ]:
# List all available table IDs
rc.list_tables()

### Get Specific DataFrames

You can retrieve specific tables as pandas DataFrames for custom analysis:

In [ ]:
# Get kernel top stats (table ID 1)
kernel_stats = rc.get_dataframe(1)
print(kernel_stats.head())

In [ ]:
# Get system info (table ID 101)
sys_info = rc.get_dataframe(101)
print(sys_info)

### Custom Analysis

Once you have the DataFrames, you can perform custom analysis:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Example: Plot kernel execution times
kernel_stats = rc.get_dataframe(1)
if kernel_stats is not None and "Mean_Duration" in kernel_stats.columns:
    plt.figure(figsize=(12, 6))
    kernel_stats.plot(x="Kernel_Name", y="Mean_Duration", kind="bar")
    plt.title("Kernel Execution Times")
    plt.xlabel("Kernel")
    plt.ylabel("Mean Duration (ns)")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

## Loading Data with Options

You can specify various options when loading data:

In [ ]:
# Load with custom options
rc.open(
    perf_data_dir,
    time_unit="us",           # Use microseconds instead of nanoseconds
    normal_unit="per_cycle",  # Normalize by cycles
    max_stat_num=20,          # Show top 20 statistics
    decimal=3                 # Use 3 decimal places
)

## Text-Based Roofline Plot

You can also display a text-based roofline plot in the terminal style using the CLI roofline generator:

In [ ]:
from utils.tty import show_roof_plot

# Access the internal analysis object to get the roofline object
analysis_obj = rc._current_analysis
if analysis_obj:
    socs = analysis_obj.get_socs()
    arch = analysis_obj.arch
    
    if socs and arch in socs and hasattr(socs[arch], "roofline_obj"):
        roofline_obj = socs[arch].roofline_obj
        
        # Generate text-based roofline plot for FP32
        # You can change "FP32" to other datatypes like "FP16", "FP64", "INT8", etc.
        roof_plot_text = roofline_obj.cli_generate_plot(
            dtype="FP32",
            workload=analysis_obj._runs[analysis_obj.dest_dir],
            config=analysis_obj._profiling_config,
            arch_config=analysis_obj._arch_configs[arch]
        )
        
        if roof_plot_text:
            print("\n" + "="*80)
            print("Text-Based Roofline Plot (FP32)")
            print("="*80)
            show_roof_plot(roof_plot_text)
        else:
            print("Roofline plot could not be generated. Check if roofline.csv exists in the data directory.")
    else:
        print("Roofline object not available. Make sure roofline data was collected during profiling.")
else:
    print("No analysis loaded. Call rc.open() first.")

## Interactive Dash Web UI

You can launch an interactive Dash web application to explore your profiling data with a rich GUI interface:

In [ ]:
import threading
import time
from IPython.display import IFrame, display

# Function to launch the Dash web UI in a separate thread
def launch_dash_ui(perf_data_dir, port=8050):
    """Launch the Dash web UI for interactive analysis."""
    import argparse
    from pathlib import Path
    from rocprof_compute_analyze.analysis_webui import webui_analysis
    from rocprof_compute_soc import soc_gfx908, soc_gfx90a, soc_gfx940, soc_gfx941, soc_gfx942, soc_gfx950
    from utils.specs import generate_machine_specs
    from utils import file_io
    
    # Create minimal args for web UI
    args = argparse.Namespace(
        path=[[perf_data_dir]],
        config_dir=str(Path("../src/rocprof_compute_soc/analysis_configs").resolve()),
        list_stats=False,
        list_metrics=None,
        list_blocks=None,
        filter_metrics=None,
        nodes=None,
        list_nodes=False,
        spatial_multiplexing=False,
        kernel_verbose=0,
        verbose=0,
        debug=False,
        time_unit="ns",
        normal_unit="per_wave",
        max_stat_num=10,
        decimal=2,
        output_format="stdout",
        output_name=None,
        no_roof=False,
        specs_correction=None,
        roofline_data_type=["FP32"],
        tui=False,
        gui=port,
        random_port=False,
        gpu_kernel=None,
        gpu_id=None,
        gpu_dispatch_id=None,
        pc_sampling_sorting_type="samples"
    )
    
    # Supported architectures
    supported_archs = {
        "gfx908": "MI100",
        "gfx90a": "MI200",
        "gfx940": "MI300A",
        "gfx941": "MI300A",
        "gfx942": "MI300X",
        "gfx950": "MI350X",
    }
    
    # Create web UI analysis instance
    webui = webui_analysis(args, supported_archs)
    
    # Load system info and generate machine specs
    sys_info = file_io.load_sys_info(f"{perf_data_dir}/sysinfo.csv")
    sys_info_dict = {key: value[0] for key, value in sys_info.to_dict("list").items()}
    mspec = generate_machine_specs(args, sys_info_dict)
    
    # Initialize SOCs
    omni_socs = {
        "gfx908": soc_gfx908.gfx908_soc(args, mspec),
        "gfx90a": soc_gfx90a.gfx90a_soc(args, mspec),
        "gfx940": soc_gfx940.gfx940_soc(args, mspec),
        "gfx941": soc_gfx941.gfx941_soc(args, mspec),
        "gfx942": soc_gfx942.gfx942_soc(args, mspec),
        "gfx950": soc_gfx950.gfx950_soc(args, mspec),
    }
    webui.set_soc(omni_socs)
    
    # Run the analysis
    webui.sanitize()
    webui.pre_processing()
    webui.run_analysis()

# Launch the Dash UI in a background thread
port = 8050
dash_thread = threading.Thread(
    target=launch_dash_ui,
    args=(perf_data_dir, port),
    daemon=True
)
dash_thread.start()

# Wait a moment for the server to start
time.sleep(3)

print(f"Dash web UI is running at http://localhost:{port}")
print("You can open this URL in your browser to interact with the GUI.")
print("\nNote: The server will continue running in the background.")
print("To stop it, restart the Jupyter kernel.")

# Display the Dash app in an iframe (optional - may not work in all environments)
# Uncomment the line below to try embedding the UI directly in the notebook
# display(IFrame(src=f"http://localhost:{port}", width=1200, height=800))

WARNING:root:roofline.csv not found.

Dash web UI is running at http://localhost:8050
You can open this URL in your browser to interact with the GUI.

Note: The server will continue running in the background.
To stop it, restart the Jupyter kernel.

WARNING:root:roofline.csv not found.
WARNING:root:roofline.csv not found.
WARNING:root:roofline.csv not found.

### Features of the Dash Web UI

The interactive Dash web application provides:

- **Interactive Filters**: Drop-down menus to filter by kernel, GPU, dispatch, and more
- **Dynamic Charts**: Interactive bar charts and tables that update based on your filters
- **Roofline Visualization**: Interactive roofline plots with zoom and pan capabilities
- **Memory Charts**: Visual representation of memory hierarchy performance
- **Real-time Updates**: The UI updates dynamically as you change filters
- **Full Metrics**: Access to all profiling metrics in an organized, visual format

**Tips:**
- Start without filters to see high-level overview metrics
- Apply kernel/dispatch filters to dive into detailed low-level metrics
- Use the normalization dropdown to change how metrics are displayed
- Hover over charts for detailed information
- The UI runs on port 8050 by default (you can change this in the code above)

## Complete Example Workflow

In [ ]:
# 1. Load data
rc.open("/path/to/workload_dir")

# 2. Show basic overview
rc.analysis(show_basic_only=True)

# 3. List available tables
rc.list_tables()

# 4. Get specific kernel data
kernel_df = rc.get_dataframe(1)

# 5. Filter and analyze specific kernels
if kernel_df is not None:
    # Get kernel IDs for the top 3 kernels by duration
    top_kernels = kernel_df.nlargest(3, "Mean_Duration").index.tolist()
    top_kernel_ids = [str(k) for k in top_kernels]
    
    # Show detailed analysis for these kernels
    rc.analysis(filter_kernel=top_kernel_ids)

## Notes

- The interface automatically detects your GPU architecture (MI100, MI200, MI300, etc.)
- Roofline analysis is displayed automatically if roofline data is available
- All Plotly charts are interactive - you can zoom, pan, and hover for details
- Use `show_basic_only=True` to see only high-level metrics without filters
- Apply filters to see detailed low-level metrics for specific kernels/GPUs/dispatches
- The text-based roofline plot provides a terminal-style visualization that can be useful for quick analysis or when working in environments without full graphics support